# Generated by Django 5.0.4 on 2024-06-17 03:51

import django.db.models.deletion
import foodApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_first_name', models.CharField(max_length=200)),
                ('cf_last_name', models.CharField(max_length=200)),
                ('cf_email', models.EmailField(max_length=200)),
                ('cf_Phone_number', models.BigIntegerField()),
                ('cf_passward', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Chef',
            },
        ),
        migrations.CreateModel(
            name='Customers1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_first_name', models.CharField(max_length=25)),
                ('c_last_name', models.CharField(max_length=25)),
                ('c_phone_number', models.BigIntegerField()),
                ('c_passward', models.CharField(max_length=200)),
                ('c_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_first_name', models.CharField(max_length=200)),
                ('d_last_name', models.CharField(max_length=200)),
                ('d_email', models.EmailField(max_length=200)),
                ('d_Phone_number', models.BigIntegerField()),
                ('d_passward', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'speciality',
            },
        ),
        migrations.CreateModel(
            name='chefAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefLocality', models.CharField(max_length=50)),
                ('chefState', models.CharField(max_length=50)),
                ('chefDistrict', models.CharField(max_length=50)),
                ('chefDivision', models.CharField(max_length=50)),
                ('chefForeign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.chef')),
            ],
        ),
        migrations.CreateModel(
            name='customerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerLocality', models.CharField(max_length=50)),
                ('customerState', models.CharField(max_length=50)),
                ('customerDistrict', models.CharField(max_length=50)),
                ('customerDivision', models.CharField(max_length=50)),
                ('customerForeign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.customers1')),
            ],
        ),
        migrations.CreateModel(
            name='foodUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('item_date', models.CharField(blank=True, default=foodApp.models.default_date, max_length=200)),
                ('item_image', models.ImageField(upload_to=foodApp.models.filepath)),
                ('cfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.chef')),
                ('chefspec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.spec')),
            ],
            options={
                'db_table': 'foodUpload',
            },
        ),
    ]
