# Generated by Django 5.0.4 on 2024-06-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalAmount',
            field=models.FloatField(default=0),
        ),
    ]
