# Generated by Django 5.0.4 on 2024-07-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0004_adminapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=100)),
                ('orderdate', models.DateField(max_length=100)),
                ('orderstatus', models.CharField(max_length=100)),
                ('custaddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.customeraddress')),
                ('custdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.customers1')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentstatus', models.CharField(default='pending', max_length=100)),
                ('transactionid', models.CharField(max_length=200)),
                ('paymentmode', models.CharField(default='paypal', max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.customers1')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.cart')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.customers1')),
                ('paymentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodApp.payment')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
    ]
