# Generated by Django 5.0.4 on 2024-07-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0005_order_payment_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='cartid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.foodupload'),
        ),
    ]
